### ISSUE TITLE
Automate adding/removing docs-missing label

### ISSUE THREAD

**Issue by balloob** [home-assistant/probot-home-assistant#17]
Automatically add/remove docs missing label on the following events:

 - If a PR is labeled in `home-assistant` with `new-integration` or `new-platform`, check if there is a link in the description linking to docs, if not, add `docs-missing` label
 - If a PR is edited in `home-assistant` repo and it has label `docs-missing` AND (`new-integration` or `new-platform`), check if it has a link to docs, if so, remove `docs-missing`
 - If a PR is opened/edited in `home-assistant.io` and it links to a `home-assistant` PR which has `docs-missing` label, remove the `docs-missing` label

**Comment by oxan** [comment]
Is still a wanted feature? I submitted esphome/probot-esphome#2 that could relatively easily be ported over to HA.

**Comment by balloob** [comment]
Yeah it would be great. 

Should we merge our probot repo's? We're very closely aligned so might as well merge the developer tools if possible.

**Comment by oxan** [comment]
> Should we merge our probot repo's? We're very closely aligned so might as well merge the developer tools if possible.

It's possible, but I don't think it's worth the effort. While the support code is the same (though ESPHome's seems to be ran differently), there's quite some divergence in the logic. To do that in a single repository would either mean sprankling ifs all over the code, or copying the plugins and having to update two every time. With two repositories it's just a matter of git merge.

There's some changes made in the supporting code of the ESPHome one that can/should be ported over the HA one though. Shouldn't be too much work.

**Comment by ludeeus** [comment]
With https://github.com/home-assistant/service-hub/pull/26 we are moving the source of the bot, if this change is still wanted please move the issue to that repository.
If not, please close it 👍
