### ISSUE TITLE
`parent-merged` label is not applied if docs PR not mentioned in PR body

### ISSUE THREAD

**Issue by balloob** [home-assistant/probot-home-assistant#21]
The `parent-merged` label is not always applied:

When a PR is merged in `home-assistant` repo where the body does not contain a link to the docs PR, the `parent-merged` label will not be added.

Example: https://github.com/home-assistant/home-assistant.io/pull/10146

**Comment by ludeeus** [comment]
With https://github.com/home-assistant/service-hub/pull/26 we are moving the source of the bot, if this change is still wanted please move the issue to that repository.
If not, please close it 👍
