### ISSUE TITLE
Add label "needs-review" to new pull requests

### ISSUE THREAD

**Issue by MartinHjelmare** [home-assistant/probot-home-assistant#35]
Add a label "needs-review" to new pull requests in the [backend repo](https://github.com/home-assistant/home-assistant). We will use this label to guard the stale bot from auto-closing PRs without a review.

See https://github.com/home-assistant/home-assistant/pull/31837

When a review is done remove label "needs-review" from the PR.

**Comment by frenck** [comment]
we have to find a way, not to just "add" this label, but automate it nicely as well. Else, we'll end up with the same situation as we are in right now.

Examples:
- Add the need review label, if the PR is opened
- Add the need review label, if a commit is added to the PR
- Remove the need review label, if a member of the org leaves a comment or review.

**Comment by MartinHjelmare** [comment]
Yes, that will give us complete coverage. But the second case isn't as needed in real world, since most reviewers will respond when commits are pushed after the first review. We do see reviewers missing updates or dropping off sometimes, so I agree that it would be good to get complete coverage for the whole flow.

**Comment by MartinHjelmare** [comment]
A more pragmatic approach could be to add or remove the label based on which list in the dev project the PR is moved to.

It would mean more manual responsibility but would limit the label change spam during the PR lifetime.

**Comment by ludeeus** [comment]
With https://github.com/home-assistant/service-hub/pull/26 we are moving the source of the bot, if this change is still wanted please move the issue to that repository.
If not, please close it 👍

**Comment by MartinHjelmare** [comment]
I think there's still a need for something like this, but it's not a priority for me.
