### ISSUE TITLE
FR: Add links to the bottom of the issue body

### ISSUE THREAD

**Issue by ludeeus** [home-assistant/probot-home-assistant#49]
Trigger: issue.labled
condition: lable starts with `integration:`

action:
  post links to:
    - The source in the codebase
    - The documentation page
    - Link to all open issues with the same label

Other links?

I think this will add more context to the issues.
I'll be happy to implement it if this is something that is wanted.

If the bottom of the body is not desired, it can be a standalone comment (like the codeowner mentions)

**Comment by balloob** [comment]
Probably better to do as a comment. Link to issues with same label is not needed, one can click on the label in the sidebar.

Could we combine it with the code owner message so we don't spam messages?

**Comment by ludeeus** [comment]
good idea, extending the codeownermention plugin is probably the best
