### ISSUE TITLE
Message about PR with incorrect target branch

### ISSUE THREAD

**Issue by klaasnicolaas** [home-assistant/probot-home-assistant#50]
Often enough I now see in the docs repo that Probot posts messages and adds labels to a PR, while this is not necessary. This is because contributors do not always directly post the urls to the core PR in the description, they often edit their PR later and then add the url.

Is there anything we can do about this? I'm removing labels more often than it actually added value.

**Improvement could be:**
Removing the labels and assignment after an edit of the description.

![image](https://user-images.githubusercontent.com/20448157/79993090-a70f5100-84b4-11ea-9499-b2e790718a37.png)

**Comment by balloob** [comment]
We run probot in a lambda, we can only do real time responses. We can't wait 5 or 10 minutes. So in that case we should remove this functionality.

**Comment by balloob** [comment]
What do you think @frenck ?

**Comment by frenck** [comment]
I think we should re-evaluate on edit..?

**Comment by ludeeus** [comment]
So if the target is correct after an update, remove the assignee and the "needs-rebase" label?

**Comment by frenck** [comment]
Yes, I would say so.
