### ISSUE TITLE
Not assigning issues to me

### ISSUE THREAD

**Issue by Bre77** [home-assistant/probot-home-assistant#79]
When I raise a PR, the bot is successfully tagging them as by-code-owner, but when someone raises an issue against my integrations ([advantage_air](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L26), [splunk](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L470)), I do not get assigned and the comment mentioning me is missing. This has resulting in me not knowing there are issues to fix until many weeks after they are raised.

https://github.com/home-assistant/core/issues/52041
https://github.com/home-assistant/core/issues/48466
https://github.com/home-assistant/core/issues/37130

**Comment by chemelli74** [comment]
You should receive a mail from GitHub each time you are tagged in a issue.
If not, check your notification profile.

Simone

**Comment by Bre77** [comment]
@chemelli74 if you look at the three issues I linked you will see I am not tagged.

**Comment by ludeeus** [comment]
There is a longstanding issue where the lambda gets terminated before posting the code owner mention.
That's one of the reasons we are migrating to https://github.com/home-assistant/bot
